### ISSUE TITLE
Payload not working on x64 machines

### ISSUE THREAD

**Issue by tapojoydas** [ChaitanyaHaritash/kimi#1]
<img width="626" alt="screen shot 2017-10-12 at 2 14 14 pm" src="https://user-images.githubusercontent.com/19535171/31486962-cd60bb04-af56-11e7-9b51-00ab8d7ac8b3.png">

This is on the target machine, which also happens to be Kali Linux.

**Comment by ChaitanyaHaritash** [comment]
thanks, for giving it a test. I've just made a hot update with another command line args to set architecture too (-a/--arch) :) do make another test and lemme know if it works all good :) ignore that error of xterm.. as i was using ssh 
![troll](https://user-images.githubusercontent.com/16261173/31495306-bc37ee38-af74-11e7-9e4e-016d2f1bc06c.PNG)
